[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 7
y = 0

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"
