[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
opacity = 0.8
blur = true

[window.padding]
x = 7
y = 0

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Tab"
chars = "\t"  # Ensure Tab sends the correct character

[env]
TERM = "xterm-256color"
