---

- name: Include Vars
  include_vars: "ubuntu.yml"

- name: Install packages on Ubuntu 
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Install rust on Ubuntu
  become: false
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
