---

- name: Check if dwm is already installed
  command: dwm -v
  register: dwm_check
  failed_when: dwm_check.rc > 1
  changed_when: false
  ignore_errors: true

- name: Install required packages
  become: yes
  apt:
    name: 
      - build-essential
      - libx11-dev 
      - libxinerama-dev 
      - sharutils
      - libxft-dev 
    state: present
  when: dwm_check.rc !=0
