---

- name: Install zsh on Ubuntu
  become: yes
  apt:
    name:
      - zsh
    state: present

- name: Set zsh as default on Ubuntu
  become: yes
  user:
    name: "{{ ansible_env.USER  }}"
    shell: /usr/bin/zsh
