- name: Install packages on Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install packages on Arch
  import_tasks: arch.yml
  when: ansible_distribution == "Archlinux"
